// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class Announcement
{
    public int AnnouncementId { get; set; }

    public int GymId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int PostedBy { get; set; }

    public DateTime PostDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string ChangeUser { get; set; }

    public virtual Gym Gym { get; set; }

    public virtual Employee PostedByNavigation { get; set; }
}