// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class CheckIn
{
    public int CheckInId { get; set; }

    public int MemberId { get; set; }

    public int GymId { get; set; }

    public DateTime CheckInTime { get; set; }

    public string ChangeUser { get; set; }

    public virtual Gym Gym { get; set; }

    public virtual Member Member { get; set; }
}