// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class ClassEnrollment
{
    public int EnrollmentId { get; set; }

    public int ClassId { get; set; }

    public int MemberId { get; set; }

    public DateTime EnrollmentDate { get; set; }

    public string Status { get; set; }

    public string ChangeUser { get; set; }

    public virtual Class Class { get; set; }

    public virtual Member Member { get; set; }
}