// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class Class
{
    public int ClassId { get; set; }

    public int GymId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int InstructorId { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime EndDateTime { get; set; }

    public int MaxCapacity { get; set; }

    public string ChangeUser { get; set; }

    public virtual ICollection<ClassEnrollment> ClassEnrollments { get; set; } = new List<ClassEnrollment>();

    public virtual Gym Gym { get; set; }

    public virtual Employee Instructor { get; set; }
}