// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class EmployeeSchedule
{
    public int ScheduleId { get; set; }

    public int EmployeeId { get; set; }

    public int GymId { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime EndDateTime { get; set; }

    public string ShiftType { get; set; }

    public string Notes { get; set; }

    public string ChangeUser { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Gym Gym { get; set; }
}