// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class EquipmentMaintenance
{
    public int MaintenanceId { get; set; }

    public int EquipmentId { get; set; }

    public DateOnly MaintenanceDate { get; set; }

    public string Description { get; set; }

    public decimal? Cost { get; set; }

    public string PerformedBy { get; set; }

    public string ChangeUser { get; set; }

    public virtual Equipment Equipment { get; set; }
}