// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class Equipment
{
    public int EquipmentId { get; set; }

    public int GymId { get; set; }

    public string Name { get; set; }

    public string Category { get; set; }

    public DateOnly PurchaseDate { get; set; }

    public decimal Cost { get; set; }

    public string Status { get; set; }

    public string ChangeUser { get; set; }

    public virtual ICollection<EquipmentMaintenance> EquipmentMaintenances { get; set; } = new List<EquipmentMaintenance>();

    public virtual Gym Gym { get; set; }
}