// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class MembershipPlan
{
    public int PlanId { get; set; }

    public int GymId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal MonthlyRate { get; set; }

    public int? DurationMonths { get; set; }

    public bool IsActive { get; set; }

    public string ChangeUser { get; set; }

    public virtual Gym Gym { get; set; }

    public virtual ICollection<MemberSubscription> MemberSubscriptions { get; set; } = new List<MemberSubscription>();
}