// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int MemberId { get; set; }

    public int? SubscriptionId { get; set; }

    public decimal Amount { get; set; }

    public DateTime PaymentDate { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public string TransactionId { get; set; }

    public virtual Member Member { get; set; }

    public virtual MemberSubscription Subscription { get; set; }
}