// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GitFit.Api.Models;

public partial class Payroll
{
    public int PayrollId { get; set; }

    public int EmployeeId { get; set; }

    public DateOnly PayPeriodStart { get; set; }

    public DateOnly PayPeriodEnd { get; set; }

    public decimal HoursWorked { get; set; }

    public decimal TotalPay { get; set; }

    public DateTime PaymentDate { get; set; }

    public string Status { get; set; }

    public virtual Employee Employee { get; set; }
}